In [1]:
import sys

from torch.utils.data import DataLoader
import torch
import torch.nn as nn
import torch.optim as optim

sys.path.insert(0, "/home/workboots/Repos/my_repos/advocate_recommendation/exp_9/adv_prediction/without_text/")

from model.net import SimpleMultiLabelPrediction
from data_generator import SimpleDataset

# Testing Dataset

In [2]:
dataset = SimpleDataset(data_paths = ["/home/workboots/Datasets/DHC/variations/new/var_4/cross_val/0_fold/with_areas/train/"],
                        targets_paths = ["/home/workboots/Datasets/DHC/variations/new/var_4/targets/with_areas/case_areas.json"],
                        unique_labels = "/home/workboots/Datasets/DHC/variations/new/var_4/area_act_chapter_section_info/with_areas/present_areas.txt")

In [3]:
dataset.unique_labels

['CRIMINAL LAW',
 'CONSTITUTIONAL LAW',
 'CIVIL LAW',
 'JUDICIARY AND COURTS LAW',
 'PROPERTY LAW',
 'NATIONAL SECURITY LAW',
 'INTELLECTUAL PROPERTY LAW',
 'CONTRACT LAW',
 'COMPANY OR BUSINESS OR CORPORATE LAW',
 'TRANSPORTATION LAW',
 'BANKING AND FINANCE LAW',
 'TAX LAW',
 'FAMILY LAW',
 'GOVERNMENT LAW',
 'HUMAN RIGHTS LAW',
 'ELECTION LAW',
 'ADMINISTRATIVE LAW',
 'INTERPRETATION OF STATUTES',
 'EDUCATION LAW',
 'INTERNATIONAL LAW',
 'MOTOR VEHICLES LAW',
 'MEDICAL AND HEALTHCARE LAW',
 'TRADE LAW',
 'IMMIGRATION LAW',
 'ENERGY LAW',
 'TELECOMMUNICATION LAW',
 'RTI LAW',
 'CYBER LAW',
 'INSURANCE LAW',
 'COMPETITION LAW',
 'ENVIRONMENT LAW',
 'MEDIA LAW',
 'CONSUMER LAW',
 'ESTATE PLANNING (WILLS AND TRUSTS) LAW',
 'AGRICULTURE LAW',
 'AVIATION LAW']

In [5]:
dataloader = DataLoader(dataset, batch_size = 12)

In [7]:
for data, target in dataloader:
    print(len(data))
    print(target.shape)

12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([12, 36])
12
torch.Size([1

KeyboardInterrupt: 

In [11]:
for data, target in dataset:
    print(target, len(target))

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) 36
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0

KeyboardInterrupt: 

# Testing model

In [3]:
model = SimpleMultiLabelPrediction(input_dim=768,
                                   labels=dataset.unique_labels,
                                   device="cuda")

In [5]:
model.device

'cuda'

In [4]:
model = model.to("cuda")

In [9]:
criterion = nn.BCELoss(reduction='sum')

In [17]:
optimizer = optim.Adam(model.parameters(), lr =3e-3)

In [18]:
data = torch.rand(16, 768)
targets = torch.rand(16, 36)
data = data.to("cuda")
targets = targets.to("cuda")

In [19]:
for i in enumerate(range(100)):
    y_pred = model(data)
    loss = criterion(y_pred, targets)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print(loss.item())

409.965087890625
406.0400390625
403.56719970703125
400.6811828613281
399.52496337890625
398.1098327636719
396.9012451171875
396.67962646484375
395.9442443847656
394.9632263183594
394.7294616699219
394.28564453125
393.5026550292969
393.4900207519531
392.6337890625
392.208251953125
391.7025146484375
390.92755126953125
390.5492248535156
389.8280029296875
389.31573486328125
388.736572265625
388.10723876953125
387.60906982421875
386.97930908203125
386.49176025390625
385.9239196777344
385.43719482421875
384.89404296875
384.4369201660156
383.8824462890625
383.48663330078125
382.966552734375
382.61187744140625
382.10870361328125
381.7532958984375
381.31170654296875
380.94134521484375
380.51898193359375
380.15655517578125
379.7662658691406
379.4254455566406
379.00555419921875
378.66607666015625
378.3092041015625
377.9655456542969
377.6326904296875
377.2994689941406
376.9716796875
376.62994384765625
376.3009948730469
375.9908447265625
375.677490234375
375.3648986816406
375.04779052734375
374.731